apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hzao3nr9h-nodejs 
  janus-idp.io/tekton: hzao3nr9h-nodejs
  backstage.io/kubernetes-id: hzao3nr9h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hzao3nr9h-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml